apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: muapp
        image: gowthamc121/jenkins-argo-cicd:v1.
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
